# Generated by Django 3.1.6 on 2021-03-30 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiretuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('tubers_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('tubers_id', models.IntegerField()),
                ('users_id', models.IntegerField(blank=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 13, 21, 12, 221888))),
            ],
        ),
    ]
