# Generated by Django 3.1.6 on 2021-03-30 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 30, 14, 20, 48, 252971)),
        ),
    ]
