# Generated by Django 3.1.6 on 2021-03-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='gotolink',
            field=models.CharField(default='', max_length=255),
        ),
    ]
